name: easy_cleaner
description: A CLI tool to clean translations files for Easy Localization package.
version: 1.0.0
environment:
  sdk: ">=3.0.5 <4.0.0"

# Add regular dependencies here.
dependencies:
  analyzer: ^5.1.0
  args: ^2.5.0
  glob: ^2.0.2

executables:
  lck: bin/easy_cleaner.dart

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
